const BUILD_FIRE_WOOD_COST = 5;
const BUILD_FIRE_ROCKS_COST = 2;
const FEED_FIRE_COST = 1;
const MAX_FIRE = 5;
const FIRE_COOLDOWN = 5;

const GATHER_WOOD_COOLDOWN = 5;

const GATHER_ROCKS_COOLDOWN = 5;

const CRAFT_POINTY_STICK_COST = 1;
const CRAFT_POINTY_STICK_COOLDOWN = 10;

const GO_HUNTING_COOLDOWN = 10;
